region: us-east-1

fromEmail: some@email.com
fromName: AIM-AHEAD

userTableArn: arn:aws:dynamodb:<region>:<account>:table/<table>/stream/<streamId>

### Lambda layer versions
### Override if using a different deployed layer version
# layer-sdk-version: 1
# layer-lodash-version: 1
