userTableArn: arn:aws:dynamodb:<region>:<account>:table/<table>/stream/<streamId>

### Lambda layer versions
### Override if using a different deployed layer version
# layer-cdk-version: 1
# layer-lodash-version: 1
