region: us-east-1

domain: some-domain.com

fromEmail: some@email.com
fromName: AIM-AHEAD

userTableName: a-table-name
userTableStream: some-stream-name
userPoolUrl: "https://cognito-idp.<region>.amazonaws.com/<pool_id>"

### Lambda layer versions
### Override if using a different deployed layer version
# layer-lodash-version: 1
