service: "swb-tools-registration-api"

frameworkVersion: "3"

provider:
  name: "aws"
  runtime: "nodejs14.x"

package:
  patterns:
    - "!node_modules/**"
    - "!package.json"
    - "!template.js"
    - "!pnpm-lock.yaml"
    - "!*.test.js"
    - "!__snapshots__/**"

custom:
  config: "${file(../../configs/${sls:stage}.yml)}"
  info: "${file(./package.json)}"
  layer-avj: "${file(../../layers/ajv/nodejs/package.json)}"
  layer-lodash: "${file(../../layers/lodash/nodejs/package.json)}"
  layer-uuid: "${file(../../layers/uuid/nodejs/package.json)}"
  userTableArn: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.config.userTableName}"

functions:
  AccountRegistrationNotification:
    handler: "src/handler.registerUser"
    name: "${self:service}-${sls:stage}"
    description: "${self:custom.info.description}"
    layers:
      - "arn:aws:lambda:${aws:region}:${aws:accountId}:layer:${layerName(${self:custom.lodash})}-${sls:stage}:1"
      - "arn:aws:lambda:${aws:region}:${aws:accountId}:layer:${layerName(${self:custom.ajv})}-${sls:stage}:1"
      - "arn:aws:lambda:${aws:region}:${aws:accountId}:layer:${layerName(${self:custom.uuid})}-${sls:stage}:1"
    iamRoleStatements:
      - Effect: "Allow"     
        Action:
          - "dynamodb:PutItem"
        Resource: "${self:custom.config.userTableArn}"
    events:
      - http:
          path: api/register
          method: post
          cors:
            origins:
              - "http://*${self:custom.config.domain}"
    environment:
      REGION: "${aws:region}"
      USER_TABLE: "${self:custom.config.userTableName}"
      USER_POOL: "${self:custom.config.userPoolUrl}"
      IDP_NAME: "${self:custom.config.registrationIDP}"
      USER_ROLE: "${self:custom.config.registrationRole}"
      USER_REASON: "${self:custom.config.registrationReason}"

plugins:
  - "serverless-iam-roles-per-function"
  - ../../layers/layerNamePlugin
