service: "swb-tools-registration-api"

frameworkVersion: "3"

provider:
  name: "aws"
  runtime: "nodejs14.x"
  apiGateway:
      request:
        schemas:
          register-user:
            name: RegisterUser
            schema: ${file(./registration.schema.json)}
            description: "A validation model for registering users."

package:
  patterns:
    - "!node_modules/**"
    - "!__snapshots__/*"
    - "!template.js"
    - "!*.test.js"
    - "!package.json"
    - "!*.schema.json"
    - "!pnpm-lock.yaml"

custom:
  config: "${file(../../configs/${sls:stage}.yml)}"
  info: "${file(./package.json)}"
  layer-uuid: "${file(../../layers/uuid/nodejs/package.json)}"
  userTableArn: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.config.userTableName}"

functions:
  AccountRegistrationNotification:
    handler: "handler.registerUser"
    name: "${self:service}-${sls:stage}"
    description: "${self:custom.info.description}"
    layers:
      - "arn:aws:lambda:${aws:region}:${aws:accountId}:layer:${layerName(${self:custom.layer-uuid})}-${sls:stage}:1"
    iamRoleStatementsName: "${self:service}-${sls:stage}-lambda"
    iamRoleStatements:
      - Effect: "Allow"     
        Action:
          - "dynamodb:PutItem"
        Resource: "${self:custom.userTableArn}"
      - Effect: "Allow"
        Action:
          - "dynamodb:Query"
        Resource: "${self:custom.userTableArn}/index/Principal"
    events:
      - http:
          path: api/register
          method: post
          request:
            schemas:
              application/json: register-user
          # cors:
          #   origins:
          #     - "http://localhost:3000"
          #     - "http://*${self:custom.config.domain}"
    environment:
      REGION: "${aws:region}"
      USER_TABLE: "${self:custom.config.userTableName}"
      USER_POOL: "${self:custom.config.userPoolUrl}"
      IDP_NAME: "${self:custom.config.registrationIDP}"
      USER_ROLE: "${self:custom.config.registrationRole}"
      USER_REASON: "${self:custom.config.registrationReason}"

plugins:
  - "serverless-iam-roles-per-function"
  - ../../layers/layerNamePlugin
