service: "swb-tools-layers"

frameworkVersion: "3"

provider:
  name: "aws"
  runtime: "nodejs14.x"
  region: "us-east-1"

custom:
  lodash: "${file(./lodash/nodejs/package.json)}"
  uuid: "${file(./uuid/nodejs/package.json)}"
  scriptable:
    hooks:
      before:package:createDeploymentArtifacts: "pnpm build-layers"

layers:
  Lodash:
    path: "lodash"
    description: "${self:custom.lodash.description}"
    name: "${layerName(${self:custom.lodash})}-${sls:stage}"
  uuid:
    path: "uuid"
    description: "${self:custom.uuid.description}"
    name: "${layerName(${self:custom.uuid})}-${sls:stage}"

plugins:
  - "serverless-scriptable-plugin"
  - ./layerNamePlugin
