service: "swb-tools-layers"

frameworkVersion: "3"

provider:
  name: "aws"
  runtime: "nodejs14.x"
  region: "us-east-1"

custom:
  lodash: "${file(./lodash/nodejs/package.json)}"
  avl: "${file(./avl/nodejs/package.json)}"
  uuid: "${file(./uuid/nodejs/package.json)}"
  scriptable:
    hooks:
      before:package:createDeploymentArtifacts: "pnpm -r install"

layers:
  Lodash:
    path: "lodash"
    description: "${self:custom.lodash.description}"
    name: "${self:custom.lodash.name}-${self:custom.lodash.version}-${sls:stage}"
  avl:
    path: "avl"
    description: "${self:custom.avl.description}"
    name: "${self:custom.avl.name}-${self:custom.avl.version}-${sls:stage}"
  uuid:
    path: "uuid"
    description: "${self:custom.uui.description}"
    name: "${self:custom.uuid.name}-${self:custom.uuid.version}-${sls:stage}"

plugins:
  - "serverless-scriptable-plugin"
