service: "swb-tools-registration-api"

frameworkVersion: "3"

provider:
  name: "aws"
  runtime: "nodejs14.x"
  region: "${self:custom.config.region}"

package:
  patterns:
    - "!node_modules/**"
    - "!package.json"
    - "!template.js"
    - "!pnpm-lock.yaml"
    - "!*.test.js"
    - "!__snapshots__/**"

custom:
  config: "${file(../../configs/${sls:stage}.yml)}"
  info: "${file(./package.json)}"
  layer-avj: "${file(../../layers/ajv/nodejs/package.json):name}"
  layer-lodash: "${file(../../layers/lodash/nodejs/package.json):name}"
  layer-uuid: "${file(../../layers/uuid/nodejs/package.json):name}"

functions:
  AccountRegistrationNotification:
    handler: "handler.notification"
    description: "${self:custom.info.description}"
    layers:
      - "arn:aws:lambda:${self:provider.region}:${aws:accountId}:layer:${self:custom.layer-ajv}-${sls:stage}:${self:custom.config.layer-ajv-version, 1}"
      - "arn:aws:lambda:${self:provider.region}:${aws:accountId}:layer:${self:custom.layer-lodash}-${sls:stage}:${self:custom.config.layer-lodash-version, 1}"
      - "arn:aws:lambda:${self:provider.region}:${aws:accountId}:layer:${self:custom.layer-uuid}-${sls:stage}:${self:custom.config.layer-uuid-version, 1}"
    iamRoleStatements:
      - Effect: "Allow"     
        Action:
          - "dynamodb:PutItem"
        Resource: "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.config.userTableName}"
    events:
      - http:
          path: api/register
          method: post
          cors:
            origins:
              - "http://*${self:custom.config.domain}"
    environment:
      REGION: "${self:provider.region}"
      USER_TABLE: "${self:custom.config.userTableName}"
      USER_POOL: "${self:custom.config.userPoolUrl}"
      IDP_NAME: "${self:custom.config.registrationIDP}"
      USER_ROLE: "${self:custom.config.registrationRole}"
      USER_REASON: "${self:custom.config.registrationReason}"

resources:
  Description: "${self:custom.info.description}"

plugins:
  - "serverless-iam-roles-per-function"