service: "swb-tools-admin-notification"

frameworkVersion: "3"

provider:
  name: "aws"
  runtime: "nodejs14.x"
  region: "${self:custom.config.region}"

package:
  patterns:
    - "!node_modules/**"
    - "!package.json"
    - "!template.js"
    - "!pnpm-lock.yaml"
    - "!*.test.js"
    - "!__snapshots__/**"

custom:
  config: "${file(../../configs/${sls:stage}.yml)}"
  info: "${file(./package.json)}"
  layer-lodash: "${file(../../layers/lodash/nodejs/package.json):name}"

functions:
  AccountRegistrationNotification:
    handler: "handler.notification"
    description: "${self:custom.info.description}"
    layers:
      - "arn:aws:lambda:${self:provider.region}:${aws:accountId}:layer:${self:custom.layer-lodash.name}-${self:custom.layer-lodash.version}-${sls:stage}:1"
    events:
      - stream:
          type: "dynamodb"
          arn: "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.config.userTableName}/stream/${self:custom.config.userTableStream}"
          # To reduce invokations and associated costs, function is invoked when one of the following conditions is met:
          # The payload size reaches 6MB, the Batch Window reaches its maximum value, or the Batch Size reaches its maximum value.
          batchSize: 10 # (default: 100, max 1000)
          batchWindow: 300 # 5 minutes (max: 5mins/300seconds)
          startingPosition: "LATEST"
          filterPatterns:
            - eventName: ["INSERT"]
              dynamodb:
                NewImage:
                  createdBy:
                    S: ["_system_"]
    iamRoleStatements:
      - Effect: "Allow"     
        Action:
          - "dynamodb:DescribeStream"
          - "dynamodb:GetRecords"
          - "dynamodb:GetShardIterator"
          - "dynamodb:ListStreams"
        Resource: "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.config.userTableName}/stream/${self:custom.config.userTableStream}"
      - Effect: "Allow"     
        Action:
          - "sns:Publish"
          - "sns:Subscribe"
        Resource: AccountRegistrationTopic
    environment:
      REGION: "${self:provider.region}"
      SNS_TOPIC: AccountRegistrationTopic

resources:
  Description: "${self:custom.info.description}"
  Resources:
    AccountRegistrationTopic:
        Type: AWS::SNS::Topic
        Properties:
          DisplayName: 'SWB account user registration notification to admins.'
          TopicName: 'swb-tools-admin-notification-topic'

plugins:
  - "serverless-iam-roles-per-function"