region: us-east-1

domain: some-domain.com

userTableName: a-table-name
userTableStream: some-stream-name
userPoolUrl: "https://cognito-idp.<region>.amazonaws.com/<pool_id>"

# Notification/User
fromEmail: some@email.com
fromName: AIM-AHEAD
emailTemplateName: userActivationTemplate

# Registration
registrationSubject: 'AIM-AHEAD - SWB User Registrations are Pending'
registrationReason: 'AIM-AHEAD participation.'
registrationIDP: 'Auth0'
registrationRole: 'researcher'