Resources:
  WAFRegionalWebACL:
    Type: "AWS::WAFv2::WebACL"
    Properties:
      Name: ${self:custom.wafName, 'WAF-DDos-and-Bot-Control'}
      Scope: REGIONAL
      Description: WAF regional web ACL to prevent HTTP flood DDos attacks and control bots.
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: "ApiGateway-HTTP-Flood-Prevent-Metric"
      Rules:
        - Name: "HTTP-Flood-Prevent-Rule"
          Priority: 0
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: ${self:custom.wafRateLimit, 500}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: "HTTP-Flood-Prevent-Rule-Metric"
        - Name: "AWS-BotControl"
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: "AWS"
              Name: "AWSManagedRulesBotControlRuleSet"
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: "AWS-BotControl-Metric"
