region: us-east-1
userTableName: a-table-name
userTableStream: '2022-07-21T18:05:23.830'

# User Notification
fromEmail: some@email.com
fromName: AIM-AHEAD
emailTemplateName: userActivationTemplate

# Admin Notification
registrationSubject: 'AIM-AHEAD - SWB User Registrations are Pending'

# Registration API
userPoolUrl: "https://cognito-idp.<region>.amazonaws.com/<pool_id>"
registrationReason: 'AIM-AHEAD participation.'
registrationIDP: 'Auth0'
registrationRole: 'researcher'
wafRateLimit: 500